spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true # Json To Object 시 알 수 없는 프로퍼티가 있을 때 에러가 발생
  datasource:
    username: yuseon
    password: yuseon
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor.sql.BasicBinder: TRACE
      springframework:
          security: DEBUG
my-app:
  admin-username: "admin@email.com"
  admin-password: "admin"
  user-username: "user@email.com"
  user-password: "user"
  client-id: "myApp"
  client-secret: "pass"

---
spring:
  profiles: test
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
